global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'myapp_metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['organization-service:8080']
