version: '3'
networks:
  organization-network:
    driver: bridge
services:
  organization-service:
    image: docker.io/vcosqui/organization-app:latest
    deploy:
      replicas: 2
    networks:
      - organization-network

  ngnix-server:
    image: nginx:1.13
    ports:
      - "8080:80"
    volumes:
      - '../../resources/nginx/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - "organization-network"
    depends_on:
      - organization-service

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - organization-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - organization-network

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    environment:
       - GF_SECURITY_ADMIN_USER=admin
       - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ../resources/grafana:/etc/grafana/provisioning
    networks:
      - organization-network
