name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Smoke Test
        #run: timeout 30 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://user:password@localhost:8080/organization)" != "200" ]]; do sleep 5; done' || false
        run: docker run --network container:ngnix-server appropriate/curl --retry 10 --retry-connrefused http://user:password@localhost:8080/organization
         
